/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Test;

/**
 * This is a class named App
 */
public class App {
    /**
     * This greets the user
     * @return greeting in string
     */
    public String getGreeting() {
        return "Hello world.";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
